### GET request to example server
GET http://127.0.0.1:8080/api/users

### GET teams
GET http://127.0.0.1:8080/api/teams

### GET team members
GET http://127.0.0.1:8080/api/teams/c81d4e2e-bcf2-11e6-869b-7df92533d2db/members