spring:
  application:
    name: orgcraft

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  datasource:
    hikari:
      auto-commit: false

  # Datasource
  sql:
    init:
      mode: always